@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Jan 24 17:37:51 +0700 2026
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim onedconv_tb_behav -key {Behavioral:sim_1:Functional:onedconv_tb} -tclbatch onedconv_tb.tcl -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_behav.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_behav1_heart.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_systolic.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_weightside.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_output.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_counters.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_OUTPUTbrams.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_CONTROL.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_weightBRAMS.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/BUG1.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_inputside.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_INPUTBRAM.wcfg -log simulate.log"
call xsim  onedconv_tb_behav -key {Behavioral:sim_1:Functional:onedconv_tb} -tclbatch onedconv_tb.tcl -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_behav.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_behav1_heart.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_systolic.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_weightside.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_output.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_counters.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_OUTPUTbrams.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_CONTROL.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_weightBRAMS.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/BUG1.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_inputside.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/onedconv_tb_INPUTBRAM.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
