@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Jan 17 18:33:23 +0700 2026
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_top_lvl_io_control_behav -key {Behavioral:sim_1:Functional:tb_top_lvl_io_control} -tclbatch tb_top_lvl_io_control.tcl -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/top_lvl_tb_behav.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/top_lvl_tb_behav1.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/top_lvl_tb_behav2.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/tb_top_lvl_io_control_behav.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/tb_top_lvl_io_control_behav_internals.wcfg -log simulate.log"
call xsim  tb_top_lvl_io_control_behav -key {Behavioral:sim_1:Functional:tb_top_lvl_io_control} -tclbatch tb_top_lvl_io_control.tcl -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/top_lvl_tb_behav.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/top_lvl_tb_behav1.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/top_lvl_tb_behav2.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/tb_top_lvl_io_control_behav.wcfg -view D:/SEMESTER1_20252026/VLSI/WGAN-EEG-FPGA/src/AXON/project_1/tb_top_lvl_io_control_behav_internals.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
