/******************************************************************************
 * Module      : cmap_buffer
 * Author      : Dharma Anargya Jowandy
 * Date        : January 2026
 *
 * Description :
 * Buffer module for the Channel Map (cmap) generated by the MM2IM mapper.
 * Captures a snapshot of the channel map and provides indexed single-bit
 * access based on a completion counter.
 *
 * Key Features :
 * - Single-Cycle Snapshot Capture
 *   Latches the incoming channel map on assertion of the load signal.
 *
 * - Combinational Indexed Output
 *   Provides zero-latency (combinational) access to a selected channel bit.
 *
 * - Counter-Based Indexing
 *   Outputs the channel map bit indexed by the 'done' counter
 *   (valid range: 1 to WIDTH).
 *
 * Parameters :
 * - WIDTH : Number of channels / PE columns (default: 16)
 *
 ******************************************************************************/


module cmap_buffer #(
    parameter WIDTH = 16  // Number of channels (PE columns)
)(
    input  wire              clk,
    input  wire              rst_n,

    // Snapshot from MM2IM
    input  wire [WIDTH-1:0]  cmap_in,
    input  wire              load,     // Load snapshot (1x per tile)

    // Selector from Transpose FSM
    input  wire [4:0]        done,     // 0..16

    // Output to Accumulation / Write-back
    output reg               cmap_out
);

    // ---------------------------------------------------------
    // Internal storage
    // ---------------------------------------------------------
    reg [WIDTH-1:0] cmap_reg;

    // ---------------------------------------------------------
    // Load snapshot
    // ---------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            cmap_reg <= {WIDTH{1'b0}};
        else if (load)
            cmap_reg <= cmap_in;
    end

    // ---------------------------------------------------------
    // Output 1-bit indexed by done (combinational, no delay)
    // ---------------------------------------------------------
    always @(*) begin
        if (done >= 5'd1 && done <= 5'd16) begin
            cmap_out = cmap_reg[done - 5'd1];
        end else begin
            cmap_out = 1'b0;
        end
    end

endmodule